version: '3.4'

services:
  webixkanban:
    image: ${DOCKER_REGISTRY-}webixkanban
    container_name: "webixkanban"
    build:
      context: .
      dockerfile: WebixKanban/Dockerfile

  sqlkanban:
    image: microsoft/mssql-server-linux
    container_name: "sqlkanban"
    environment:
      SA_PASSWORD: "SqlDevOps2017"
      ACCEPT_EULA: "Y"
    ports:
      - "1431:1433"
